name: Deploy & Run DLT Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'health_dlt_pipeline.py'
      - '.github/workflows/deploy_dlt_pipeline.yml'
    branches:
      - devops
      - main
jobs:
  deploy-dlt:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install databricks-sdk databricks-cli
          pip install databricks-sdk
           pip install pyspark 
           pip install databricks-dlt
           pip install --upgrade databricks-sdk


      - name: Run DLT Pipeline Script
        run: |
          #python health_dlt_pipeline.py
          python trigger_dlt_pipeline.py
          #python dlt.py


